import { DocumentStatus, DocumentType } from '@prisma/client';
import { prisma } from './db';

const allowedTypes = new Set(['application/pdf', 'image/png', 'image/jpeg']);
export function validatePrivateFile(input: { mimeType: string; sizeBytes: number; storageKey: string }) { if (!allowedTypes.has(input.mimeType)) throw new Error('DOCUMENT_TYPE_NOT_ALLOWED'); if (input.sizeBytes <= 0 || input.sizeBytes > 10 * 1024 * 1024) throw new Error('DOCUMENT_SIZE_INVALID'); if (!/^[a-zA-Z0-9/_-]+$/.test(input.storageKey) || input.storageKey.includes('..')) throw new Error('DOCUMENT_KEY_INVALID'); }
export async function listMyDocuments(userId: string) { return prisma.document.findMany({ where: { student: { userId }, status: DocumentStatus.PUBLISHED }, select: { id: true, type: true, issuedAt: true, status: true, createdAt: true } }); }
export async function issueDocument(adminId: string, input: { studentId: string; internshipId?: string; type: DocumentType; storageKey: string; mimeType: string; sizeBytes: number }) { validatePrivateFile(input); const document = await prisma.document.create({ data: { studentId: input.studentId, internshipId: input.internshipId, issuedById: adminId, type: input.type, storageKey: input.storageKey, issuedAt: new Date(), status: DocumentStatus.DRAFT } }); await prisma.auditEvent.create({ data: { actorId: adminId, action: 'DOCUMENT_ISSUED', entity: 'Document', entityId: document.id, metadata: { type: input.type } } }); return document; }
export async function publishDocument(adminId:string,id:string){const d=await prisma.document.update({where:{id},data:{status:DocumentStatus.PUBLISHED,issuedAt:new Date()}});await prisma.auditEvent.create({data:{actorId:adminId,action:'DOCUMENT_PUBLISHED',entity:'Document',entityId:id,metadata:{}}});return d;}
export async function revokeDocument(adminId:string,id:string){const d=await prisma.document.update({where:{id},data:{status:DocumentStatus.REVOKED}});await prisma.auditEvent.create({data:{actorId:adminId,action:'DOCUMENT_REVOKED',entity:'Document',entityId:id,metadata:{}}});return d;}
export async function authorizeDocumentDownload(userId:string,id:string){const d=await prisma.document.findFirst({where:{id,status:DocumentStatus.PUBLISHED,student:{userId}},select:{id:true,type:true,storageKey:true}});if(!d)throw new Error('DOCUMENT_NOT_FOUND');if(!process.env.OBJECT_STORAGE_SIGNING_KEY)throw new Error('DOCUMENT_STORAGE_NOT_CONFIGURED');return {documentId:d.id,type:d.type,downloadUrl:`/api/documents/${d.id}/content`};}
